Solution
mate-academy/py-taxi-service-forms pull request #311
Opened 2023-06-16 20:14 UTC by the-andrew-007

![1](https://github.com/mate-academy/py-taxi-service-forms/assets/114390841/64dbbcd6-8885-42bd-a3cc-974733b2df41)
![2](https://github.com/mate-academy/py-taxi-service-forms/assets/114390841/a7ebab50-c030-451a-86dc-a9a5b8ebba71)
![3](https://github.com/mate-academy/py-taxi-service-forms/assets/114390841/92885929-a66a-4518-8505-38c445a38043)
![4](https://github.com/mate-academy/py-taxi-service-forms/assets/114390841/6d849401-08a7-46e4-9498-71a19af863d4)
![5](https://github.com/mate-academy/py-taxi-service-forms/assets/114390841/9d3b2c04-4430-45e8-a538-6b3aee58df72)
![7](https://github.com/mate-academy/py-taxi-service-forms/assets/114390841/7287809e-1b44-4bf2-91aa-ed32e1981f89)

2023-06-21 12:02 UTC, vasylhnatiuk requested changes

2023-06-21 12:02 UTC, vasylhnatiuk commented on taxi/urls.py
> +    path("car/create", CreateCarView.as_view(), name="car-create"),
```suggestion
    path("car/create/", CreateCarView.as_view(), name="car-create"),
```

2023-06-21 12:02 UTC, vasylhnatiuk commented on taxi/urls.py
> +    path("car/<int:pk>/update", UpdateCarView.as_view(), name="car-update"),
```suggestion
    path("car/<int:pk>/update/", UpdateCarView.as_view(), name="car-update"),
```

2023-06-21 12:02 UTC, vasylhnatiuk commented on taxi/urls.py
> +    path("car/<int:pk>/delete", DeleteCarView.as_view(), name="car-delete"),
```suggestion
    path("car/<int:pk>/delete/", DeleteCarView.as_view(), name="car-delete"),
```

2023-06-21 12:02 UTC, vasylhnatiuk commented on taxi/urls.py
> +    path("car/<int:pk>/delete", DeleteCarView.as_view(), name="car-delete"),
add here and in all of path

2023-06-28 14:29 UTC, ArsenPidhoretskyi approved these changes
Well done!

2024-04-17 17:04 UTC, closed without merging